Remove some unnecessary modules
Azure-Samples/spring-petclinic-microservices pull request #56
Opened 2023-04-17 03:09 UTC by zmssp

1. Update the jvm options. "Xmx2g" is too big for a 2G instance, change it to "-Xms1536m -Xmx1536m".
2. Remove module "config server", config server is managed by Azure Spring Apps, we do not need customer to create config server.
3. Remove module "spring-admin", ASA does not have a good support for spring admin, we should not use it in our code samples.

2023-04-17 07:26 UTC, felipmiguel requested changes
There are some modules that are part of the original sample and they are necessary in case you want to test it locally.

2023-04-18 02:48 UTC, zmssp commented
> There are some modules that are part of the original sample and they are necessary in case you want to test it locally.

Revert changes for "config server" and "admin".

1. Update the jvm options.
2. Do not deploy admin to asa

2023-05-02 21:50 UTC, felipmiguel requested changes
Please, don't remove the original projects from pom.xml as they can be used in different scenarios, not only in Azure Spring Apps.

2023-05-02 21:50 UTC, felipmiguel commented on pom.xml
I wouldn't remove spring-petclinic-admin-server nor spring-petclinic-config-server from pom.xml and I'll continue building. If the application is deployed locally can be necessary both. If it is removed because they are already provided by Azure Spring Apps, then discovery-server shouldn't be build and deployed either.

2023-05-02 21:50 UTC, felipmiguel commented on README.md
Looks good to me

2023-05-04 02:22 UTC, zmssp commented on pom.xml
It makes sense, just forget this pr

2023-05-04 02:22 UTC, closed without merging