Support deploy-to-azure button for enterprise plan
Azure-Samples/spring-petclinic-microservices pull request #67
Opened 2023-08-28 09:59 UTC by moarychan

Sync code from https://github.com/Azure/azure-quickstart-templates/pull/13532

Try this button:
| Deploy to Azure Spring Apps | |
|--|--|
| Consumption plan   |Not support|
| Basic/Standard plan|Not support|
| Enterprise plan    |[![Deploy to Azure](https://aka.ms/deploytoazurebutton)](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fmoarychan%2Fspring-petclinic-microservices%2Fpr-demo%2Finfra%2Fazuredeploy.json)|

2023-08-29 07:56 UTC, saragluna requested changes

2023-08-29 07:56 UTC, saragluna commented on infra/scripts/deploy-jar-to-asa.sh
> +set -Eeuo pipefail
Do we need this script for the e plan?

2023-08-29 07:57 UTC, saragluna commented on README.md
> +| Basic/Standard plan|Not support|
```suggestion
| Consumption plan   |Not supported|
| Basic/Standard plan|Not supported|
```

2023-08-31 07:30 UTC, moarychan commented
Hi @stliu , please help review this PR, thanks!

2023-09-01 02:11 UTC, stliu approved these changes

2023-09-01 02:11 UTC, merged